name: timer_controller
description: A timer library that provides controls (play, pause, restart, etc)
  and widgets to consume the timer value.
version: 1.0.0
homepage: https://github.com/MattisBrizard/timer_controller

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
