name: timer_controller
description: A timer library that provides controls (play, pause, etc) and widgets to consume the timer value.
version: 0.1.0
author: Mattis Brizard
homepage: https://github.com/MattisBrizard/timer_controller

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
