name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Remove generated files from coverage
        uses: daalbano/lcov-action@v1
        with:
          remove_patterns: freezed

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash

      - name: Enable flutter web
        run: flutter config --enable-web

      - name: Build
        run: |
          cd example
          flutter pub get
          flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
